// Create / edit a campaign. Numeric fields are coerced on save; cycles are
// (re)generated by the store from the date window.
import { useState } from 'react'
import { useStore } from '../store/useStore'
import { emptyCampaign, CATEGORIES, POOL_RISK_LEVELS } from '../lib/schema'

export default function CampaignForm({ initial, onDone }) {
  const cards = useStore((s) => s.doc.cards)
  const upsertCampaign = useStore((s) => s.upsertCampaign)
  const [d, setD] = useState(initial || emptyCampaign(cards[0]?.card_id || ''))

  const set = (k, v) => setD({ ...d, [k]: v })

  function save() {
    upsertCampaign({
      ...d,
      min_spend_threshold: Number(d.min_spend_threshold) || 0,
      earning_rate: Number(d.earning_rate) || 0,
      cashback_cap: Number(d.cashback_cap) || 0,
    })
    onDone?.()
  }

  return (
    <div className="space-y-2 rounded border border-slate-200 bg-white p-3 text-xs">
      <input
        placeholder="Campaign title"
        value={d.title}
        onChange={(e) => set('title', e.target.value)}
        className="w-full rounded border border-slate-300 px-2 py-1"
      />
      <div className="grid grid-cols-2 gap-2">
        <select value={d.associated_card_id} onChange={(e) => set('associated_card_id', e.target.value)} className="rounded border border-slate-300 px-2 py-1">
          <option value="">— card —</option>
          {cards.map((c) => <option key={c.card_id} value={c.card_id}>{c.bank} {c.name}</option>)}
        </select>
        <select value={d.category} onChange={(e) => set('category', e.target.value)} className="rounded border border-slate-300 px-2 py-1">
          {CATEGORIES.map((c) => <option key={c}>{c}</option>)}
        </select>
        <label className="text-slate-500">Start
          <input type="date" value={d.start_date} onChange={(e) => set('start_date', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1" />
        </label>
        <label className="text-slate-500">End
          <input type="date" value={d.end_date} onChange={(e) => set('end_date', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1" />
        </label>
        <label className="text-slate-500">Min spend (RM)
          <input type="number" step="0.01" value={d.min_spend_threshold} onChange={(e) => set('min_spend_threshold', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1" />
        </label>
        <label className="text-slate-500">Earning rate (0–1)
          <input type="number" step="0.01" value={d.earning_rate} onChange={(e) => set('earning_rate', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1" />
        </label>
        <label className="text-slate-500">Cashback cap (RM)
          <input type="number" step="0.01" value={d.cashback_cap} onChange={(e) => set('cashback_cap', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1" />
        </label>
        <label className="text-slate-500">Cap period
          <select value={d.cap_period} onChange={(e) => set('cap_period', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1">
            <option value="monthly">monthly</option>
            <option value="campaign">whole campaign</option>
          </select>
        </label>
        <label className="text-slate-500">Pool risk
          <select value={d.pool_risk_level} onChange={(e) => set('pool_risk_level', e.target.value)} className="mt-0.5 block w-full rounded border border-slate-300 px-2 py-1">
            {POOL_RISK_LEVELS.map((p) => <option key={p}>{p}</option>)}
          </select>
        </label>
        <label className="flex items-center gap-2 text-slate-500">
          <input type="checkbox" checked={d.is_fcfs} onChange={(e) => set('is_fcfs', e.target.checked)} />
          First-come-first-served
        </label>
      </div>
      <div className="flex gap-2">
        <button onClick={save} className="rounded bg-indigo-600 px-3 py-1 font-medium text-white">Save</button>
        <button onClick={onDone} className="rounded border border-slate-300 px-3 py-1">Cancel</button>
      </div>
    </div>
  )
}
